# Generated by Django 4.2 on 2024-04-01 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_name',
            field=models.CharField(default=2.2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=2.4, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
