# Generated by Django 4.2 on 2024-04-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon_name_order_tax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='amount_products',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=3.3, max_digits=8),
            preserve_default=False,
        ),
    ]
